path_to_files: /g/data/ra94/mayank-de-novo
assembly_method: de-novo   #de-novo reference-genome reference-transcriptome?
ref_genome: Kabuli_UWA-v2.6.3
blastx_subject: blastx-input/uniprot_sprot.fasta
blastx_link: ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz  
min_transcript_length: "150"
RNAsamba_training_set: rnasamba-input/partial_length_weights.hdf5 
RNAsamba_training_link: https://raw.githubusercontent.com/apcamargo/RNAsamba/master/data/full_length_weights.hdf5 #curl -O https://raw.githubusercontent.com/apcamargo/RNAsamba/master/data/partial_length_weights.hdf5
samples:
       - polyA_minus_sample_1
       - polyA_minus_sample_2
       - polyA_minus_sample_3
       - polyA_minus_sample_4
       - polyA_minus_sample_5
       - polyA_minus_sample_6
       - polyA_minus_sample_7
       - polyA_minus_sample_8
       - polyA_minus_sample_9
       - polyA_minus_sample_10
       - polyA_minus_sample_11
       - polyA_minus_sample_12
       - polyA_plus_sample_1
       - polyA_plus_sample_2
       - polyA_plus_sample_3
       - polyA_plus_sample_4
       - polyA_plus_sample_5
       - polyA_plus_sample_6
       - polyA_plus_sample_7
       - polyA_plus_sample_8
       - polyA_plus_sample_9
       - polyA_plus_sample_10
       - polyA_plus_sample_11
       - polyA_plus_sample_12
