name: rna-seq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastp
  - samtools
  - rsem
  - bowtie
  - trinity
  - detonate
  - blast
  - yq
  - rnasamba
  - snakemake
  - python
