name: rna-seq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastp
  - star
  - cufflinks
  - snakemake=5.10
  - cookiecutter
  - htseq
  - samtools
  - rsem
  - bowtie
  - trinity
  - parallel  
