#!/bin/bash
#PBS -P ra94
#PBS -q normal
#PBS -l walltime=04:00:00,mem=100MB,ncpus=1
#PBS -l wd
#PBS -N job
#PBS -lstorage=scratch/ra94
#PBS -V
eval "$(conda shell.bash hook)"
set +u
conda activate rna-seq
set -u
snakemake --unlock
snakemake all --profile cluster --no-hooks --cluster-config config/cluster-config.json --use-conda
